spring.application.name=url-shortener

# Default profile
spring.profiles.default=dev

# Common JPA settings
spring.jpa.open-in-view=false

# Application
app.base-url=${APP_BASE_URL:http://localhost:8080}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.info.env.enabled=true

# Application information
info.app.name=URL Shortener
info.app.description=Production-style URL shortening service
info.app.version=0.0.1

# Server
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

# Compression
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/plain,text/css,text/javascript
server.compression.min-response-size=1024

# Request limits
server.max-http-request-header-size=16KB